name: "Deploy to s3"
on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Configure aws"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
    - uses: actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: "Deploy to s3"
      run: npm run deploy
